### ISSUE TITLE
Problema amb linux amb bit4ipki drivers smartcard

### ISSUE THREAD

**Issue by serk7** [ConsorciAOC/signador#10]
Es curios, a e-justicia puc firmar sense cap problema: 
```
[OSName] Sistema operatiu: Linux2019-02-01 12:43:06 INFO  LoggingConfig:30 - [OSName] Sistema operatiu: Linux
[AppletSignatura] Desem el certificat amb el que s'estï¿½ realitzant la signatura2019-02-01 12:43:06 INFO  LoggingConfig:30 - [AppletSignatura] Desem el certificat amb el que s'estï¿½ realitzant la signatura
[javascript] its called: onSignOK2019-02-01 12:43:08 INFO  LoggingConfig:30 - [javascript] its called: onSignOK
[javascript] its called: onMultiSignOK2019-02-01 12:43:08 INFO  LoggingConfig:30 - [javascript] its called: onMultiSignOK
```

Pero quan intento firmar a gencat o a altres llocs tinc aquest problema:
```
No existeix el fitxer :C:\Windows\System32\bit4ipki.dll2019-02-01 13:08:49 INFO  LoggingConfig:30 - No existeix el fitxer :C:\Windows\System32\bit4ipki.dll

[javascript] its called: onSignError2019-02-01 13:08:49 INFO  LoggingConfig:30 - [javascript] its called: onSignError
```

Resum:

A e-justicia, em busca el fitxer /usr/lib/libbit4ipki.so el troba i llavors em demana la clau de la smart card i tot seguit em surt el certificat per la firma. Firma amb normalitat.

A la pagina de la generalitat o del ajuntament busca el fitxer C:\Windows\System32\bit4ipki.dll amb la consecuencia de que no el troba i per tant no carrega la smartcard.

No entenc quina diferencia, pero a e-justicia busca la llibreria correcta per el meu sistema operatiu pero en altres webs busca la llibreria de windows que logicament a linux no existeix.

Que podria fer? em podrieu ajudar? 

Merci si em podeu ajudar.

**Comment by albciff** [comment]
Hola @serk7 , el problema és la integració que fan la gent de justícia. El signador rep un paràmetre en funció de l'aplicació integrada, en aquest cas l'aplicació de justícia estan passant el paràmetre per a linux, però en canvi l'aplicació de la generalitat no ho està fent. 

Em podries indicar quina és l'aplicació que no funciona, d'aquest manera els hi demanaré que passin també el paràmetre corresponent per a linux.

Gràcies,

**Comment by serk7** [comment]
La que se segur es: 
**concilicacions de gencat**
https://conciliacions.gencat.cat/gescon_internet/AppJava/pagelogin.do

Un altre que vaig tindre el mateix problema era una página del ajuntament. Intentare buscarla i reportarla. Ara que se quin es el problema, anire probant i reportan aquelles que trobi que intentin carregar el signador per windows.

Moltisimes gracies, poder firmar desde linux ens ajudaria moltisim aqui a la meva feina, ja que traballem tots amb linux i tenim que mantenir un windows per aquestes  coses. Seria un plaer poder precindi del windows.

**Comment by albciff** [comment]
Hola @serk7 com que esta sent difícil que les aplicacions integrades passin el paràmetre correcte per a la càrrega de llibreries de cara a la propera versió he afegit un paràmetre per tal que l'usuari si vol pugui indicar el path de la llibreria del PKCS11 per a poder signar, en els propers dies distribuiré la versió per a que la puguis provar. Gràcies i disculpa les molesties.

**Comment by serk7** [comment]
Moltísimes gracies! 
De totes maneres, no sería mes sencill si el propi Signador detectes en quin sistema operatiu esta funcionant i carregues uns path o uns altres?

De totes maneres la solucio que heu trobat es mes que satisfactoria per mi. Esperant la nova build.

**Comment by albciff** [comment]
Hola @serk7, la release ja està desplegada a producció per si la vols descarregar i provar.

El nou paràmetre que hauries d'afegir està explicat aquí. 

https://github.com/ConsorciAOC/signador/blob/master/guiaUsuaris/FAQs.md#problemes-amb-la-c%C3%A0rrega-de-claus-en-altres-dispositius-via-pkcs11-targessmartcards

Qualsevol cosa ja em dius. Moltes gràcies per el feedback i la paciència. Salut!
