### ISSUE TITLE
manca root.crt indicat per la documentació

### ISSUE THREAD

**Issue by xavidp** [ConsorciAOC/signador#12]
Hola:

He seguit els passos de la documentació per instal·lar el Signador ( http://consorciaoc.github.io/signador/guiaUsuaris/nativa.html ). 

Tinc Kubuntu 18.04 64 bits. He executat l'instal.lador amb "bash AppNativaSignador-x64.sh". Aparentment tot s'ha instal·lat bé, però en intentar importar el certificat que diu la documentació, no trobo "root.crt" a la carpeta indicada (/home/elmeuusuariSignador/lib/certificate/) sinó només "cacerts". I en importar-ho no passa res.

**Comment by jtmolon** [comment]
Hola,

Tuve el mismo problema de no encontrar el certificado. Tenéis que ejecutar la aplicación para que el certificado sea "extraído" o algo parecido.

`/home/elmeuusuariSignador/Signador`

Después de hacerlo, el certificado root.crt apareció en la carpeta indicada.

Saludos

**Comment by albciff** [comment]
Hola, disculpeu, el certificat `root.crt` per un tema de seguretat es diferent en cada instal·lació i es genera quan executes l'aplicació per primera vegada tal i com indica en @jtmolon 

En el cas d'ubuntu un cop instal·lat l'aplicació s'ha d'arrencar manualment, per això segurament no el trobés, afegeixo l'explicació a la documentació. Salutacions.
