### ISSUE TITLE
Error a la documentació

### ISSUE THREAD

**Issue by lepalom** [ConsorciAOC/signador#17]
En aquest enllaç:

https://github.com/ConsorciAOC/signador/blob/master/guiaUsuaris/nativa.md#52-firefox

poseu:

> En cas de problemes amb l'execució de l'aplicació nativa podeu obrir una petició a través del nostre portal de suport fent una descripció del problema, i afegint la següent informació: sistema operatiu, navegador, i si és possible els fitxers amb els logs de l'execució que podeu trobar en el path de la instal·lació de la nativa a $SIGNADOR_HOME/log/webappTemp.log i $SIGNADOR_HOME/error.log.

El portal de suport no admet fitxers .log

> error.log - Sorry, this file extension is not permitted for security reasons.

**Comment by albciff** [comment]
Hola @lepalom ,

Pots canviar l'extensió de .log a .txt abans d'adjuntar el fitxer al formulari.

Moltes gràcies,

**Comment by lepalom** [comment]
D'acord, però posa-ho a la documentació, que és el que dic en el issue.

**Comment by albciff** [comment]
Tens raó, ara ho afegeixo. Gràcies.
