### ISSUE TITLE
Ubuntu 64 i navegador Chrome

### ISSUE THREAD

**Issue by litusb** [ConsorciAOC/signador#21]
Bona tarda,

He de signar uns documents des del meu terminal i només trobo informació per fer servir aquest programa en Linux amb el navegador Firefox. És possible fer-ho servir amb el navegador Chrome?

Gràcies

**Comment by albciff** [comment]
Hola @litusb,

Em sap greu però en Linux, el programari només dona suport a les claus del magatzem de firefox.
