### ISSUE TITLE
Petició de característica: Desinstal·lador

### ISSUE THREAD

**Issue by narcisgarcia** [ConsorciAOC/signador#9]
Bé sigui que estigui documentat el procediment, o bé sigui que s'instal·li un llançador .desktop de desinstal·lació.

**Comment by albciff** [comment]
Hola @narcisgarcia , disculpa la demora en la resposta. Tens raó, el procès de desinstal·lació no està documentat, però a la carpeta on s'instal·la existeix un executable o script depenent del sistema operatiu per a dur a terme la desinstal·lació de forma automàtica.

**Comment by narcisgarcia** [comment]
Així doncs, quina de les solucions s'ha adoptat?
